package pro.fazeclan.river.stupid_express.role.neutral;

import dev.doctor4t.trainmurdermystery.api.Role;
import dev.doctor4t.trainmurdermystery.client.gui.RoleAnnouncementTexts;
import lombok.Getter;
import lombok.Setter;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.level.Level;
import org.agmas.harpymodloader.Harpymodloader;
import org.ladysnake.cca.api.v3.component.ComponentKey;
import org.ladysnake.cca.api.v3.component.ComponentRegistry;
import org.ladysnake.cca.api.v3.component.sync.AutoSyncedComponent;
import pro.fazeclan.river.stupid_express.StupidExpress;

public class NeutralRoleWorldComponent implements AutoSyncedComponent {
    public static final ComponentKey<NeutralRoleWorldComponent> KEY =
            ComponentRegistry.getOrCreate(StupidExpress.id("neutral_role_world"), NeutralRoleWorldComponent.class);
    private final Level level;
    @Getter
    @Setter
    private Role winningRole = null;

    public NeutralRoleWorldComponent(Level level) {
        this.level = level;
    }

    public void sync() {
        NeutralRoleWorldComponent.KEY.sync(this.level);
    }

    public RoleAnnouncementTexts.RoleAnnouncementText getWinningText() {
        return Harpymodloader.autogeneratedAnnouncements.get(this.winningRole);
    }

    public boolean hasNeutralWinner() {
        return this.winningRole != null;
    }

    public void reset() {
        this.winningRole = null;
    }

    @Override
    public void readFromNbt(CompoundTag tag, HolderLookup.Provider registryLookup) {
        var roleID = tag.contains("winning_role") ? tag.getString("winning_role") : "none";
        if (roleID.equals("none")) {
            this.winningRole = null;
        } else {
            this.winningRole = StupidExpress.getROLES().get(roleID);
        }
    }

    @Override
    public void writeToNbt(CompoundTag tag, HolderLookup.Provider registryLookup) {
        var role = hasNeutralWinner() ? this.winningRole.identifier().getPath() : "none";
        tag.putString("winning_role", role);
    }
}
